services:
  gophkeeper-postgres:
    image: postgres:18-alpine3.23
    container_name: gophkeeper-postgres
    environment:
      POSTGRES_DB: gophkeeper
      POSTGRES_USER: gophkeeper
      POSTGRES_PASSWORD: gophkeeper
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5435:5432"
    volumes:
      - gophkeeper_pg_data:/var/lib/postgresql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophkeeper"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gophkeeper_pg_data:
    name: gophkeeper_pg_data