// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/pkg/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Типы секретов
type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED SecretType = 0
	SecretType_SECRET_TYPE_CREDENTIALS SecretType = 1 // логин/пароль
	SecretType_SECRET_TYPE_TEXT        SecretType = 2 // произвольный текст
	SecretType_SECRET_TYPE_BINARY      SecretType = 3 // бинарные данные
	SecretType_SECRET_TYPE_BANK_CARD   SecretType = 4 // банковская карта
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_CREDENTIALS",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BINARY",
		4: "SECRET_TYPE_BANK_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED": 0,
		"SECRET_TYPE_CREDENTIALS": 1,
		"SECRET_TYPE_TEXT":        2,
		"SECRET_TYPE_BINARY":      3,
		"SECRET_TYPE_BANK_CARD":   4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_internal_pkg_proto_gophkeeper_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Основная структура секрета
type Secret struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_OwnerId       *string                `protobuf:"bytes,2,opt,name=owner_id,json=ownerId"`
	xxx_hidden_Type          SecretType             `protobuf:"varint,3,opt,name=type,enum=gophkeeper.SecretType"`
	xxx_hidden_Title         *string                `protobuf:"bytes,4,opt,name=title"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,5,opt,name=encrypted_data,json=encryptedData"`
	xxx_hidden_Meta          *string                `protobuf:"bytes,6,opt,name=meta"`
	xxx_hidden_Version       int64                  `protobuf:"varint,7,opt,name=version"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_IsDeleted     bool                   `protobuf:"varint,10,opt,name=is_deleted,json=isDeleted"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Secret) GetOwnerId() string {
	if x != nil {
		if x.xxx_hidden_OwnerId != nil {
			return *x.xxx_hidden_OwnerId
		}
		return ""
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Secret) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *Secret) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *Secret) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Secret) GetIsDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IsDeleted
	}
	return false
}

func (x *Secret) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *Secret) SetOwnerId(v string) {
	x.xxx_hidden_OwnerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *Secret) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *Secret) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *Secret) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *Secret) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *Secret) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *Secret) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Secret) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Secret) SetIsDeleted(v bool) {
	x.xxx_hidden_IsDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *Secret) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Secret) HasOwnerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Secret) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Secret) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Secret) HasEncryptedData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Secret) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Secret) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Secret) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Secret) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Secret) HasIsDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *Secret) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Secret) ClearOwnerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OwnerId = nil
}

func (x *Secret) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Title = nil
}

func (x *Secret) ClearEncryptedData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EncryptedData = nil
}

func (x *Secret) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Meta = nil
}

func (x *Secret) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Version = 0
}

func (x *Secret) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Secret) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Secret) ClearIsDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_IsDeleted = false
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *string
	OwnerId       *string
	Type          *SecretType
	Title         *string
	EncryptedData []byte
	Meta          *string
	Version       *int64
	CreatedAt     *timestamppb.Timestamp
	UpdatedAt     *timestamppb.Timestamp
	IsDeleted     *bool
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = b.Id
	}
	if b.OwnerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_OwnerId = b.OwnerId
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Title = b.Title
	}
	if b.EncryptedData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_EncryptedData = b.EncryptedData
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	if b.IsDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_IsDeleted = *b.IsDeleted
	}
	return m0
}

// Запросы и ответы
type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email       *string                `protobuf:"bytes,1,opt,name=email"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterRequest) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Email = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    *string
	Password *string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Email = b.Email
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email       *string                `protobuf:"bytes,1,opt,name=email"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Email = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Email = b.Email
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type AuthResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken  *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_ExpiresIn    int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *AuthResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.xxx_hidden_ExpiresIn
	}
	return 0
}

func (x *AuthResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AuthResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AuthResponse) SetExpiresIn(v int64) {
	x.xxx_hidden_ExpiresIn = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AuthResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthResponse) HasExpiresIn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthResponse) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AccessToken = nil
}

func (x *AuthResponse) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RefreshToken = nil
}

func (x *AuthResponse) ClearExpiresIn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ExpiresIn = 0
}

type AuthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken  *string
	RefreshToken *string
	ExpiresIn    *int64
}

func (b0 AuthResponse_builder) Build() *AuthResponse {
	m0 := &AuthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	if b.ExpiresIn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ExpiresIn = *b.ExpiresIn
	}
	return m0
}

type RefreshTokenRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *RefreshTokenRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RefreshTokenRequest) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RefreshTokenRequest) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RefreshToken = nil
}

type RefreshTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken *string
}

func (b0 RefreshTokenRequest_builder) Build() *RefreshTokenRequest {
	m0 := &RefreshTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	return m0
}

type CreateSecretRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type          SecretType             `protobuf:"varint,1,opt,name=type,enum=gophkeeper.SecretType"`
	xxx_hidden_Title         *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData"`
	xxx_hidden_Meta          *string                `protobuf:"bytes,4,opt,name=meta"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CreateSecretRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *CreateSecretRequest) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *CreateSecretRequest) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *CreateSecretRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *CreateSecretRequest) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *CreateSecretRequest) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *CreateSecretRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateSecretRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateSecretRequest) HasEncryptedData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateSecretRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateSecretRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *CreateSecretRequest) ClearEncryptedData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedData = nil
}

func (x *CreateSecretRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Meta = nil
}

type CreateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type          *SecretType
	Title         *string
	EncryptedData []byte
	Meta          *string
}

func (b0 CreateSecretRequest_builder) Build() *CreateSecretRequest {
	m0 := &CreateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Title = b.Title
	}
	if b.EncryptedData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_EncryptedData = b.EncryptedData
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Meta = b.Meta
	}
	return m0
}

type GetSecretRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetSecretRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetSecretRequest_builder) Build() *GetSecretRequest {
	m0 := &GetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ListSecretsRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Page           int32                  `protobuf:"varint,1,opt,name=page"`
	xxx_hidden_PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize"`
	xxx_hidden_IncludeDeleted bool                   `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSecretsRequest) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *ListSecretsRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ListSecretsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IncludeDeleted
	}
	return false
}

func (x *ListSecretsRequest) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ListSecretsRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListSecretsRequest) SetIncludeDeleted(v bool) {
	x.xxx_hidden_IncludeDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ListSecretsRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListSecretsRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListSecretsRequest) HasIncludeDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListSecretsRequest) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Page = 0
}

func (x *ListSecretsRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PageSize = 0
}

func (x *ListSecretsRequest) ClearIncludeDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IncludeDeleted = false
}

type ListSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Page           *int32
	PageSize       *int32
	IncludeDeleted *bool
}

func (b0 ListSecretsRequest_builder) Build() *ListSecretsRequest {
	m0 := &ListSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Page = *b.Page
	}
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.IncludeDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_IncludeDeleted = *b.IncludeDeleted
	}
	return m0
}

type ListSecretsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets     *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	xxx_hidden_Total       int32                  `protobuf:"varint,2,opt,name=total"`
	xxx_hidden_Page        int32                  `protobuf:"varint,3,opt,name=page"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *ListSecretsResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *ListSecretsResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *ListSecretsResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

func (x *ListSecretsResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListSecretsResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ListSecretsResponse) HasTotal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListSecretsResponse) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListSecretsResponse) ClearTotal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Total = 0
}

func (x *ListSecretsResponse) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Page = 0
}

type ListSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
	Total   *int32
	Page    *int32
}

func (b0 ListSecretsResponse_builder) Build() *ListSecretsResponse {
	m0 := &ListSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	if b.Total != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Total = *b.Total
	}
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Page = *b.Page
	}
	return m0
}

type UpdateSecretRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Title         *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData"`
	xxx_hidden_Meta          *string                `protobuf:"bytes,4,opt,name=meta"`
	xxx_hidden_Version       int64                  `protobuf:"varint,5,opt,name=version"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateSecretRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateSecretRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *UpdateSecretRequest) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *UpdateSecretRequest) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UpdateSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *UpdateSecretRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *UpdateSecretRequest) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *UpdateSecretRequest) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *UpdateSecretRequest) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *UpdateSecretRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateSecretRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateSecretRequest) HasEncryptedData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateSecretRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateSecretRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateSecretRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateSecretRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *UpdateSecretRequest) ClearEncryptedData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedData = nil
}

func (x *UpdateSecretRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Meta = nil
}

func (x *UpdateSecretRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = 0
}

type UpdateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *string
	Title         *string
	EncryptedData []byte
	Meta          *string
	Version       *int64
}

func (b0 UpdateSecretRequest_builder) Build() *UpdateSecretRequest {
	m0 := &UpdateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Title = b.Title
	}
	if b.EncryptedData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_EncryptedData = b.EncryptedData
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type DeleteSecretRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Permanent   bool                   `protobuf:"varint,2,opt,name=permanent"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteSecretRequest) GetPermanent() bool {
	if x != nil {
		return x.xxx_hidden_Permanent
	}
	return false
}

func (x *DeleteSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeleteSecretRequest) SetPermanent(v bool) {
	x.xxx_hidden_Permanent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteSecretRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteSecretRequest) HasPermanent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteSecretRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *DeleteSecretRequest) ClearPermanent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Permanent = false
}

type DeleteSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Permanent *bool
}

func (b0 DeleteSecretRequest_builder) Build() *DeleteSecretRequest {
	m0 := &DeleteSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Permanent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Permanent = *b.Permanent
	}
	return m0
}

type SyncRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastSync *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync,json=lastSync"`
	xxx_hidden_KnownIds []string               `protobuf:"bytes,2,rep,name=known_ids,json=knownIds"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRequest) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSync
	}
	return nil
}

func (x *SyncRequest) GetKnownIds() []string {
	if x != nil {
		return x.xxx_hidden_KnownIds
	}
	return nil
}

func (x *SyncRequest) SetLastSync(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastSync = v
}

func (x *SyncRequest) SetKnownIds(v []string) {
	x.xxx_hidden_KnownIds = v
}

func (x *SyncRequest) HasLastSync() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSync != nil
}

func (x *SyncRequest) ClearLastSync() {
	x.xxx_hidden_LastSync = nil
}

type SyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastSync *timestamppb.Timestamp
	KnownIds []string
}

func (b0 SyncRequest_builder) Build() *SyncRequest {
	m0 := &SyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LastSync = b.LastSync
	x.xxx_hidden_KnownIds = b.KnownIds
	return m0
}

type SyncResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets    *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	xxx_hidden_DeletedIds []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *SyncResponse) GetDeletedIds() []string {
	if x != nil {
		return x.xxx_hidden_DeletedIds
	}
	return nil
}

func (x *SyncResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

func (x *SyncResponse) SetDeletedIds(v []string) {
	x.xxx_hidden_DeletedIds = v
}

type SyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets    []*Secret
	DeletedIds []string
}

func (b0 SyncResponse_builder) Build() *SyncResponse {
	m0 := &SyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	x.xxx_hidden_DeletedIds = b.DeletedIds
	return m0
}

var File_internal_pkg_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_internal_pkg_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"#internal/pkg/proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto\"\xdf\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.gophkeeper.SecretTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\x0eencrypted_data\x18\x05 \x01(\fR\rencryptedData\x12\x12\n" +
	"\x04meta\x18\x06 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\n" +
	" \x01(\bR\tisDeleted\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"u\n" +
	"\fAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x92\x01\n" +
	"\x13CreateSecretRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.SecretTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x12ListSecretsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12'\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bR\x0eincludeDeleted\"m\n" +
	"\x13ListSecretsResponse\x12,\n" +
	"\asecrets\x18\x01 \x03(\v2\x12.gophkeeper.SecretR\asecrets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\x90\x01\n" +
	"\x13UpdateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"C\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tpermanent\x18\x02 \x01(\bR\tpermanent\"c\n" +
	"\vSyncRequest\x127\n" +
	"\tlast_sync\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\x12\x1b\n" +
	"\tknown_ids\x18\x02 \x03(\tR\bknownIds\"]\n" +
	"\fSyncResponse\x12,\n" +
	"\asecrets\x18\x01 \x03(\v2\x12.gophkeeper.SecretR\asecrets\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds*\x8f\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SECRET_TYPE_CREDENTIALS\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x03\x12\x19\n" +
	"\x15SECRET_TYPE_BANK_CARD\x10\x042\xd8\x01\n" +
	"\vAuthService\x12A\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x18.gophkeeper.AuthResponse\x12;\n" +
	"\x05Login\x12\x18.gophkeeper.LoginRequest\x1a\x18.gophkeeper.AuthResponse\x12I\n" +
	"\fRefreshToken\x12\x1f.gophkeeper.RefreshTokenRequest\x1a\x18.gophkeeper.AuthResponse2\xb3\x03\n" +
	"\rKeeperService\x12C\n" +
	"\fCreateSecret\x12\x1f.gophkeeper.CreateSecretRequest\x1a\x12.gophkeeper.Secret\x12=\n" +
	"\tGetSecret\x12\x1c.gophkeeper.GetSecretRequest\x1a\x12.gophkeeper.Secret\x12N\n" +
	"\vListSecrets\x12\x1e.gophkeeper.ListSecretsRequest\x1a\x1f.gophkeeper.ListSecretsResponse\x12C\n" +
	"\fUpdateSecret\x12\x1f.gophkeeper.UpdateSecretRequest\x1a\x12.gophkeeper.Secret\x12G\n" +
	"\fDeleteSecret\x12\x1f.gophkeeper.DeleteSecretRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\vSyncSecrets\x12\x17.gophkeeper.SyncRequest\x1a\x18.gophkeeper.SyncResponseB<Z2github.com/galogen13/gophkeeper/internal/pkg/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_internal_pkg_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_pkg_proto_gophkeeper_proto_goTypes = []any{
	(SecretType)(0),               // 0: gophkeeper.SecretType
	(*Secret)(nil),                // 1: gophkeeper.Secret
	(*RegisterRequest)(nil),       // 2: gophkeeper.RegisterRequest
	(*LoginRequest)(nil),          // 3: gophkeeper.LoginRequest
	(*AuthResponse)(nil),          // 4: gophkeeper.AuthResponse
	(*RefreshTokenRequest)(nil),   // 5: gophkeeper.RefreshTokenRequest
	(*CreateSecretRequest)(nil),   // 6: gophkeeper.CreateSecretRequest
	(*GetSecretRequest)(nil),      // 7: gophkeeper.GetSecretRequest
	(*ListSecretsRequest)(nil),    // 8: gophkeeper.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 9: gophkeeper.ListSecretsResponse
	(*UpdateSecretRequest)(nil),   // 10: gophkeeper.UpdateSecretRequest
	(*DeleteSecretRequest)(nil),   // 11: gophkeeper.DeleteSecretRequest
	(*SyncRequest)(nil),           // 12: gophkeeper.SyncRequest
	(*SyncResponse)(nil),          // 13: gophkeeper.SyncResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_internal_pkg_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.Secret.type:type_name -> gophkeeper.SecretType
	14, // 1: gophkeeper.Secret.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: gophkeeper.Secret.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: gophkeeper.CreateSecretRequest.type:type_name -> gophkeeper.SecretType
	1,  // 4: gophkeeper.ListSecretsResponse.secrets:type_name -> gophkeeper.Secret
	14, // 5: gophkeeper.SyncRequest.last_sync:type_name -> google.protobuf.Timestamp
	1,  // 6: gophkeeper.SyncResponse.secrets:type_name -> gophkeeper.Secret
	2,  // 7: gophkeeper.AuthService.Register:input_type -> gophkeeper.RegisterRequest
	3,  // 8: gophkeeper.AuthService.Login:input_type -> gophkeeper.LoginRequest
	5,  // 9: gophkeeper.AuthService.RefreshToken:input_type -> gophkeeper.RefreshTokenRequest
	6,  // 10: gophkeeper.KeeperService.CreateSecret:input_type -> gophkeeper.CreateSecretRequest
	7,  // 11: gophkeeper.KeeperService.GetSecret:input_type -> gophkeeper.GetSecretRequest
	8,  // 12: gophkeeper.KeeperService.ListSecrets:input_type -> gophkeeper.ListSecretsRequest
	10, // 13: gophkeeper.KeeperService.UpdateSecret:input_type -> gophkeeper.UpdateSecretRequest
	11, // 14: gophkeeper.KeeperService.DeleteSecret:input_type -> gophkeeper.DeleteSecretRequest
	12, // 15: gophkeeper.KeeperService.SyncSecrets:input_type -> gophkeeper.SyncRequest
	4,  // 16: gophkeeper.AuthService.Register:output_type -> gophkeeper.AuthResponse
	4,  // 17: gophkeeper.AuthService.Login:output_type -> gophkeeper.AuthResponse
	4,  // 18: gophkeeper.AuthService.RefreshToken:output_type -> gophkeeper.AuthResponse
	1,  // 19: gophkeeper.KeeperService.CreateSecret:output_type -> gophkeeper.Secret
	1,  // 20: gophkeeper.KeeperService.GetSecret:output_type -> gophkeeper.Secret
	9,  // 21: gophkeeper.KeeperService.ListSecrets:output_type -> gophkeeper.ListSecretsResponse
	1,  // 22: gophkeeper.KeeperService.UpdateSecret:output_type -> gophkeeper.Secret
	15, // 23: gophkeeper.KeeperService.DeleteSecret:output_type -> google.protobuf.Empty
	13, // 24: gophkeeper.KeeperService.SyncSecrets:output_type -> gophkeeper.SyncResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_pkg_proto_gophkeeper_proto_init() }
func file_internal_pkg_proto_gophkeeper_proto_init() {
	if File_internal_pkg_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_gophkeeper_proto_rawDesc), len(file_internal_pkg_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_pkg_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_pkg_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_internal_pkg_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_internal_pkg_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_internal_pkg_proto_gophkeeper_proto = out.File
	file_internal_pkg_proto_gophkeeper_proto_goTypes = nil
	file_internal_pkg_proto_gophkeeper_proto_depIdxs = nil
}
